exclude: dataclass_and_pandas|test_ejemplo.py|pydantic_test|encapsulation-composition.py|encapsulation-composition.py|codewars|dataclass_inheritance_return|dataclass_example2.py|context_manager.py


repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
    language_version: python3.10
- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
  - id: black
    args: [--safe, --quiet, --line-length, "100"]
    language_version: python3.10
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    language_version: python3.10
  - id: end-of-file-fixer
    language_version: python3.10
  - id: check-yaml
    language_version: python3.10
  - id: debug-statements
    language_version: python3.10
- repo: https://github.com/pycqa/flake8.git
  rev: 6.0.0
  hooks:
  - id: flake8
    language_version: python3.10
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.0
  hooks:
  - id: pyupgrade
    language_version: python3.10

#
#- repo: https://github.com/pre-commit/mirrors-mypy
#  rev: v0.931
#  hooks:
#  - id: mypy
#    verbose: true
#    args: [--show-error-codes]
#    additional_dependencies: ['types-requests']
