# Generated by Django 5.0.2 on 2024-02-13 19:42
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("alpha_code", models.CharField(max_length=3, primary_key=True, serialize=False)),
                ("numeric_code", models.IntegerField()),
                ("name", models.CharField(max_length=32)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Asia", "Asia"),
                            ("Europe", "Europe"),
                            ("Africa", "Africa"),
                            ("Oceania", "Oceania"),
                            ("Americas", "Americas"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("street_name", models.CharField(max_length=64)),
                ("number", models.IntegerField()),
                ("zip_code", models.IntegerField()),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_quickstart_app.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=256, null=True)),
                ("birth_date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_quickstart_app.address",
                    ),
                ),
                (
                    "birth_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_quickstart_app.country",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["first_name"], name="django_quic_first_n_d693fd_idx"),
                    models.Index(fields=["last_name"], name="django_quic_last_na_1153fb_idx"),
                ],
            },
        ),
    ]
